# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1a\n\nAPIRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"/\n\x0b\x41PIResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x10\n\x08is_audio\x18\x02 \x01(\x08\x32\x46\n\nAPIService\x12\x38\n\x07\x43\x61llAPI\x12\x13.example.APIRequest\x1a\x14.example.APIResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APIREQUEST']._serialized_start=26
  _globals['_APIREQUEST']._serialized_end=52
  _globals['_APIRESPONSE']._serialized_start=54
  _globals['_APIRESPONSE']._serialized_end=101
  _globals['_APISERVICE']._serialized_start=103
  _globals['_APISERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
